version: 0.2
env:
  variables:
    BRANCH: "master"

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - curr_working_dir=`pwd`
      - export PIP_CONFIG_FILE=$curr_working_dir/pip.conf
      - BRANCH=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed 's/refs\/heads\///')
      - |
        if [ "${BRANCH}" = "" ] ; then
          BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')
        fi
      - echo branch $BRANCH
      - |
        if [ "${BRANCH}" = "master" ] ; then
          pip install s3pypi==0.11.1
        fi
        pip install wheel
  build:
    commands:
      - |
        if [ "${BRANCH}" = "master" ] ; then
          python setup.py sdist bdist_wheel
        fi
  post_build:
    commands:
      - |
        if [ "${BRANCH}" = "master" ] ; then
          s3pypi --bucket pypi.fourzero.one --force
        fi
